apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: iw8zymrd4-go 
  janus-idp.io/tekton: iw8zymrd4-go
  backstage.io/kubernetes-id: iw8zymrd4-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: iw8zymrd4-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml